#!/usr/bin/env python3
"""
render_og_image.py — regenerate `assets/og-image.html` and `og-image.png`
from `claims.json`.

`og-image.png` is the OpenGraph/Twitter card image referenced by
`index.html` (og:image / twitter:image / Product JSON-LD `image`),
`schema.html` and `documentation.html`. It used to be a hand-made binary
with no source and no way to catch drift — the pre-rebuild version still
said `cosmetics-skincare-database.pages.dev` and quoted 19,847 products
long after both were wrong.

This script fixes that the same way `scripts/generate_seo_pages.py` fixes
landing pages: the HTML is generated from `claims.json`, committed as a
plain-text artefact so `tests/test_public_claims.py` can gate its numbers
like any other public surface, and then rendered to a PNG at the exact
1200x630 OpenGraph size with Playwright.

Run this any time `claims.json` changes, so the social-preview image never
advertises a stale count again.

Usage:  PYTHONUTF8=1 python scripts/render_og_image.py
"""

import json
from pathlib import Path

from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parent.parent
CLAIMS_PATH = ROOT / "claims.json"
HTML_PATH = ROOT / "assets" / "og-image.html"
PNG_PATH = ROOT / "og-image.png"
HOST = "incidb.dataengineered.io"

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>INCIDB Complete — OpenGraph card source</title>
<!--
  Generated by scripts/render_og_image.py from claims.json — do not hand-edit
  the numbers below; re-run the script instead. This file is rendered to
  og-image.png at 1200x630 and is itself gated by tests/test_public_claims.py
  so the social-preview image cannot drift from the measured counts.
-->
<style>
    :root {{
        --bg-main: #0A0B0E;
        --bg-card: #161922;
        --border-subtle: #232838;
        --accent-blue: #38BDF8;
        --accent-cyan: #06B6D4;
        --text-primary: #F8FAFC;
        --text-secondary: #94A3B8;
        --text-muted: #64748B;
    }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    html, body {{
        width: 1200px;
        height: 630px;
        background: var(--bg-main);
        font-family: 'Space Grotesk', -apple-system, BlinkMacSystemFont, sans-serif;
        overflow: hidden;
    }}
    .top-bar {{
        position: absolute;
        top: 0; left: 0; right: 0;
        height: 6px;
        background: linear-gradient(90deg, var(--accent-blue), var(--accent-cyan));
    }}
    .canvas {{ position: relative; width: 1200px; height: 630px; padding: 72px 80px; }}
    .wordmark {{
        font-family: 'JetBrains Mono', monospace;
        font-size: 34px;
        font-weight: 700;
        color: var(--text-primary);
        letter-spacing: 0.5px;
    }}
    .host {{
        margin-top: 10px;
        font-family: 'JetBrains Mono', monospace;
        font-size: 18px;
        color: var(--text-secondary);
    }}
    .title {{
        margin-top: 46px;
        font-size: 44px;
        font-weight: 700;
        line-height: 1.18;
        color: var(--text-primary);
        max-width: 980px;
    }}
    .title .accent {{ color: var(--accent-blue); }}
    .subtitle {{ margin-top: 18px; font-size: 21px; color: var(--text-secondary); }}
    .stats {{ margin-top: 34px; display: flex; gap: 18px; }}
    .stat {{
        background: var(--bg-card);
        border: 1px solid var(--border-subtle);
        border-radius: 10px;
        padding: 16px 22px;
        min-width: 190px;
    }}
    .stat .value {{ font-size: 30px; font-weight: 700; color: var(--text-primary); white-space: nowrap; }}
    .stat .label {{ margin-top: 4px; font-size: 15px; color: var(--text-secondary); }}
    .footline {{ margin-top: 26px; font-size: 16px; color: var(--text-muted); }}
</style>
</head>
<body>
    <div class="canvas">
        <div class="top-bar"></div>
        <div class="wordmark">INCIDB COMPLETE</div>
        <div class="host">{host}</div>
        <div class="title">The Skincare &amp; Cosmetics<br><span class="accent">INCI Database</span></div>
        <div class="subtitle">Normalised label composition data &middot; CSV + Apache Parquet</div>
        <div class="stats">
            <div class="stat">
                <div class="value">{products}</div>
                <div class="label">Products</div>
            </div>
            <div class="stat">
                <div class="value">{ingredients}</div>
                <div class="label">Canonical Ingredients</div>
            </div>
            <div class="stat">
                <div class="value">{brands}</div>
                <div class="label">Brands</div>
            </div>
            <div class="stat">
                <div class="value">{links}</div>
                <div class="label">Label Links</div>
            </div>
        </div>
        <div class="footline">CosIng functions for {functions_link_weighted_pct}% of ingredient occurrences &middot; ODbL + CosIng open data</div>
    </div>
</body>
</html>
"""


def render_html():
    claims = json.loads(CLAIMS_PATH.read_text(encoding="utf-8"))
    return TEMPLATE.format(
        host=HOST,
        products=f"{claims['products']:,}",
        ingredients=f"{claims['ingredients']:,}",
        brands=f"{claims['brands']:,}",
        links=f"{claims['links']:,}",
        functions_link_weighted_pct=claims["functions_link_weighted_pct"],
    )


def main():
    html = render_html()
    HTML_PATH.parent.mkdir(parents=True, exist_ok=True)
    HTML_PATH.write_text(html, encoding="utf-8")
    print(f"wrote {HTML_PATH}")

    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(viewport={"width": 1200, "height": 630})
        page.goto(HTML_PATH.resolve().as_uri())
        page.screenshot(path=str(PNG_PATH))
        browser.close()
    print(f"wrote {PNG_PATH}")


if __name__ == "__main__":
    main()
